### ISSUE TITLE
Предложение для дополнительного функционала

### ISSUE THREAD

**Issue by TeodorDre** [nikolamarkelov/countmyspace#1]
Добавить отдельную кнопку, которая копирует содержимое textarea в буфер обмена.

**Comment by TeodorDre** [comment]
Кнопку из пункта **3.2** можно кстати даже поставить просто рядом с кнопкой `.area__clean` 

И сделать что-то в стиле "Clean all whitespaces".

**Comment by nikolamarkelov** [comment]
Немного почистил эту issue. Прошу выносить разные предложения в разные ишью :)
Добавил возможность сохранения текста в буфер обмена.
